### ISSUE TITLE
Error when using NPCs without any senses

### ISSUE THREAD

**Issue by rlach** [JDCalvert/FVTT-PF2e-Rules-Based-NPC-Vision#6]
At least I assume this is due to no senses. I have an NPC with whom you can reproduce it with 100% rate(but I've encountered the issue with more NPCs).

Find "Chops (3-4)" in bestiary browser, try adding it to the scene and the following error will appear in the console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
[Detected 4 packages: pf2e-rules-based-npc-vision, lib-wrapper, system:pf2e, perfect-vision]
    at NPCPF2e.npcVisionLevel (npcvision.js:20:67)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:595:14)
    at NPCPF2e.🎁CONFIG.PF2E.Actor.documentClasses.npc.prototype.visionLevel#getter (libWrapper-wrapper.js:368:19)
    at NPCPF2e.get hasLowLightVision [as hasLowLightVision] (main.bundle.js:1:155117)
    at TokenDocumentPF2e.get hasLowLightVision [as hasLowLightVision] (main.bundle.js:19:170241)
    at TokenDocumentPF2e.prepareNpcDerivedData (npcvision.js:43:80)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at TokenDocumentPF2e.🎁CONFIG.Token.documentClass.prototype.prepareDerivedData#perfect-vision (pf2e.js:9:9)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at TokenDocumentPF2e.🎁CONFIG.Token.documentClass.prototype.prepareDerivedData#0 (libWrapper-wrapper.js:189:20)
    at TokenDocumentPF2e.prepareData (foundry.js:10766:10)
    at TokenDocumentPF2e.prepareData (main.bundle.js:19:170833)
    at ScenePF2e.prepareEmbeddedDocuments (foundry.js:10788:11)
    at ScenePF2e.prepareData (foundry.js:10765:10)
    at ClientDatabaseBackend._handleCreateEmbeddedDocuments (foundry.js:10068:12)
    at ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:9961:17)
    at async Function.createDocuments (document.mjs:338:21)
    at async Function.create (document.mjs:439:21)
```

After the error the scene canvas will stop updating until it's refreshed by chaning scene, and also the NPC won't be possible to move as long as the token remains on the scene.

After I give such NPC darkvision, for example, it starts working properly. This is probably an issue only with some of the NPCs, since I can give "Chops" a space as sense, save it, and then it starts working, so it seems like the field might be undefined, or an empty string, and the first case is not being handled.

Versions:
Foundry 9, build 266
pf2e: 3.8.3
npc vision: 1.0.1

**Comment by JDCalvert** [comment]
Fixed in release 1.0.2. Thanks for the report!
